services:
  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6380:6379"  # Меняем внешний порт на 6380
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
