services:
  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6380:6379"  # Меняем внешний порт на 6380
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1,local:redis:6379:2,local:redis:6379:3,local:redis:6379:4,local:redis:6379:5,local:redis:6379:6,local:redis:6379:7,local:redis:6379:8,local:redis:6379:9,local:redis:6379:10,local:redis:6379:11,local:redis:6379:12,local:redis:6379:13,local:redis:6379:14,local:redis:6379:15
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
